# Generated by Django 3.2.18 on 2023-05-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=23)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('sc_id', models.IntegerField()),
            ],
            options={
                'db_table': 'appointment',
                'managed': False,
            },
        ),
    ]
