# Generated by Django 3.2.18 on 2023-05-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('dr_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=122)),
                ('age', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=22)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'doctor',
                'managed': False,
            },
        ),
    ]
