# Generated by Django 3.2.18 on 2023-05-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Massege',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                # ('hi_id', models.IntegerField()),
                ('message', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'db_table': 'massege',
                'managed': False,
            },
        ),
    ]
