# Generated by Django 3.2.18 on 2023-05-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInspector',
            fields=[
                ('hi_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=233)),
                ('phone', models.CharField(max_length=12)),
                ('age', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'health_inspector',
                'managed': False,
            },
        ),
    ]
