# Generated by Django 3.2.18 on 2023-05-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('n_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('notification', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'notification',
                'managed': False,
            },
        ),
    ]
