# Generated by Django 3.2.18 on 2023-05-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('lab_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=33)),
                ('name', models.CharField(max_length=333)),
                ('address', models.CharField(max_length=333)),
                ('mail', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'lab',
                'managed': False,
            },
        ),
    ]
