# Generated by Django 3.2.18 on 2023-05-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('sc_id', models.AutoField(primary_key=True, serialize=False)),
                ('dr_id', models.IntegerField()),
                ('time', models.TimeField()),
                ('day', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'schedule',
                'managed': False,
            },
        ),
    ]
