# Generated by Django 3.2.18 on 2023-05-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=23)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=23)),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
    ]
